spring:
    profiles:
        active: 
        - dev
--- 
server:
  port: 8003
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept8003-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml
   type-aliases-package: com.atguigu.springcloud.entities
   mapper-locations: classpath:mybatis/mapper/**/*.xml


eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   
  instance:
   instance-id: dept-8003.com
   prefer-ip-address: true


info:
 app.name: atguigu-microservicecloud-springcloudconfig01
 company.name: www.atguigu.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$
---
server:
  port: 8003
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept8003-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml
   type-aliases-package: com.atguigu.springcloud.entities
   mapper-locations: classpath:mybatis/mapper/**/*.xml


eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   
  instance:
   instance-id: dept-8003.com
   prefer-ip-address: true


info:
 app.name: atguigu-microservicecloud-springcloudconfig01
 company.name: www.atguigu.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$