spring:
    profiles:
       active:
       - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: eureka7001.com 

---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: eureka7001.com 
