spring:
    profiles:
       active:
       - dev
---
server:
  port: 7002
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka7002-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    hostname: eureka7002.com 

---
server:
  port: 7002
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka7002-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    hostname: eureka7002.com 
