spring:
    profiles:
       active:
       - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka7001-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    hostname: eureka7001.com 

---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka7001-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    hostname: eureka7001.com 
