spring:
    profiles:
       active:
       - dev
---
server:
  port: 7003
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka7003-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    hostname: eureka7003.com 

---
server:
  port: 7003
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka7003-client

eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    hostname: eureka7003.com 
