spring:
    profiles:
       active:
       - dev
---
server: 
  port: 9527
 
spring: 
  profiles: dev
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
#  ignored-services: microservicecloud-dept
  prefix: /neu
  ignored-services: "*"
  routes: 
    mygoods.serviceId: microservicecloud-goods
    mygoods.path: /mygoods/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server: 
  port: 9527
 
spring: 
  profiles: test
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
#  ignored-services: microservicecloud-dept
  prefix: /neu
  ignored-services: "*"
  routes: 
    mygoods.serviceId: microservicecloud-goods
    mygoods.path: /mygoods/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
